exynos: audiohal_comv1: Partially revert "Fix compile error"
This partially reverts commit e91b0e1687f9b18b3dd222df0863a92f71f174cf,
since it has a fatal mistake. It gets rid of the DEVICE_BT_SCO_HEADSET
return value setting and breaking from get_device_id() for Bluetooth SCO
cases, so DEVICE_USB_HEADSET is returned instead and SCO is broken.

The -Wswitch compilation error is specifically for this case:
hardware/samsung_slsi-linaro/exynos/libaudio/audiohal_comv1/common_audiohal/audio_hw.c:650:22: error: case value not in enumerated type 'audio_devices_t' [-Werror,-Wswitch]
  650 |                 case AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET|AUDIO_DEVICE_OUT_SPEAKER:
      |                      ^
So, keep that case out and only bring back the return value and
breaking.

In the initial 13 version of the HAL, the error is simply silenced.
Still, the case does seem likely(?) dubious.

Change-Id: I9a301e79ff73fe4e9f121f3fa74c0e0fc676dc5d